Repository StackStorm/st2-dockerfiles, pull requests merged in 2018-10, with the labels that each got.

#2 Update Docker Hub badge
  README.md
Labels: RFR, bug

#10 Add new st2scheduler image since st2 3.0
  st2scheduler/Dockerfile
Labels: RFR, feature

#11 Replace some spaces with tabs in Makefile
  Makefile
Labels: RFR

#12 Don't try to reconnect to st2 DB/MQ on failure and instead exit
  .gitignore
  base/files/st2.tmp.conf
Labels: enhancement

#13 Deploy images to docker hub using CI
  .circleci/config.yml
Labels: CI/CD, RFR, enhancement

#14 Fix Docker layer caching to check the newer image versions to pull
  Makefile
Labels: CI/CD, RFR, bug
